# Generated by Django 5.2.4 on 2025-09-02 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0004_alter_domain_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Default Banner', max_length=100)),
                ('has_reject_button', models.BooleanField(default=True)),
                ('show_preferences_button', models.BooleanField(default=True)),
                ('title', models.CharField(default='We use cookies 🍪', max_length=255)),
                ('description', models.TextField(default='We use cookies to improve your experience...')),
                ('accept_text', models.CharField(default='Accept all', max_length=50)),
                ('reject_text', models.CharField(default='Reject', max_length=50)),
                ('prefs_text', models.CharField(default='Preferences', max_length=50)),
                ('position', models.CharField(choices=[('bottom', 'Bottom'), ('top', 'Top'), ('modal', 'Modal')], default='bottom', max_length=20)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=20)),
                ('primary_color', models.CharField(default='#2563eb', max_length=20)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='domains.domain')),
            ],
        ),
    ]
