# Generated by Django 5.2.4 on 2025-09-03 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cookie_policy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='privacy_policy_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('bar', 'Bar'), ('modal', 'Modal'), ('popup', 'Popup')], default='bar', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='banner',
            name='position',
            field=models.CharField(choices=[('top', 'Top'), ('bottom', 'Bottom'), ('top-left', 'Top Left'), ('top-right', 'Top Right'), ('bottom-left', 'Bottom Left'), ('bottom-right', 'Bottom Right'), ('center', 'Center')], default='bottom', max_length=20),
        ),
    ]
