# Generated by Django 5.2.4 on 2025-09-14 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0002_banner_cookie_policy_url_banner_privacy_policy_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='overlay_color',
            field=models.CharField(default='#000000', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='overlay_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='banner',
            name='overlay_opacity',
            field=models.FloatField(default=0.5),
        ),
    ]
