# Generated by Django 5.2.4 on 2025-09-17 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0003_banner_overlay_color_banner_overlay_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='background_opacity',
            field=models.FloatField(default=1.0, help_text='Opacity of the banner box (0-1)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='border_color',
            field=models.CharField(default='#E5E7EB', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='border_radius_px',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='banner',
            name='border_width_px',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='banner',
            name='height',
            field=models.CharField(blank=True, help_text="CSS length for height, e.g. '64px', 'auto'. Empty = auto", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='max_width',
            field=models.CharField(blank=True, help_text="CSS length cap for content, e.g. 'lg', '640px', '36rem'", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='overlay_blur_px',
            field=models.PositiveSmallIntegerField(default=0, help_text='CSS backdrop blur in px (0 = none)'),
        ),
        migrations.AddField(
            model_name='banner',
            name='padding_x_px',
            field=models.PositiveSmallIntegerField(default=16),
        ),
        migrations.AddField(
            model_name='banner',
            name='padding_y_px',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AddField(
            model_name='banner',
            name='shadow',
            field=models.CharField(choices=[('none', 'None'), ('sm', 'Small'), ('md', 'Medium'), ('lg', 'Large'), ('xl', 'Extra Large'), ('custom', 'Custom')], default='md', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='shadow_custom',
            field=models.CharField(blank=True, help_text="Custom CSS box-shadow, used when shadow='custom'", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='spacing_px',
            field=models.PositiveSmallIntegerField(default=12, help_text='Gap between text and buttons'),
        ),
        migrations.AddField(
            model_name='banner',
            name='text_align',
            field=models.CharField(choices=[('left', 'Left'), ('center', 'Center'), ('right', 'Right')], default='left', max_length=10),
        ),
        migrations.AddField(
            model_name='banner',
            name='width',
            field=models.CharField(blank=True, help_text="CSS length for width, e.g. '320px', '24rem', 'auto'. Empty = default", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='banner',
            name='z_index',
            field=models.IntegerField(default=10),
        ),
    ]
