# Generated by Django 5.2.4 on 2025-09-25 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0004_banner_background_opacity_banner_border_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='cookie_policy_url',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='description',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='max_width',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='privacy_policy_url',
        ),
        migrations.AlterField(
            model_name='banner',
            name='background_opacity',
            field=models.FloatField(default=1.0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='height',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='overlay_blur_px',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='shadow_custom',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='spacing_px',
            field=models.PositiveSmallIntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='banner',
            name='width',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
