# Generated by Django 5.2.4 on 2025-09-25 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0005_remove_banner_cookie_policy_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='description',
            field=models.TextField(default='We use cookies to improve your experience…'),
        ),
    ]
