# Generated by Django 5.2.4 on 2025-09-25 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0006_banner_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='accept_text_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='prefs_text_color',
            field=models.CharField(default='#111827', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='reject_text_color',
            field=models.CharField(default='#111827', max_length=20),
        ),
    ]
