# Generated by Django 5.2.4 on 2025-09-25 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0007_banner_accept_text_color_banner_prefs_text_color_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banner',
            old_name='primary_color',
            new_name='accept_bg_color',
        ),
        migrations.AddField(
            model_name='banner',
            name='prefs_bg_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='reject_bg_color',
            field=models.CharField(default='#ffffff', max_length=20),
        ),
    ]
