# Generated by Django 5.2.4 on 2025-09-28 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0008_rename_primary_color_banner_accept_bg_color_and_more'),
        ('domains', '0004_alter_domain_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='domain',
        ),
        migrations.AddField(
            model_name='banner',
            name='domains',
            field=models.ManyToManyField(blank=True, related_name='banners', to='domains.domain'),
        ),
    ]
