# Generated by Django 5.2.4 on 2025-09-29 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0009_remove_banner_domain_banner_domains'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='banner',
            name='type',
            field=models.CharField(choices=[('bar', 'Bar'), ('modal', 'Modal'), ('panel', 'Panel')], default='bar', max_length=20),
        ),
    ]
