# Generated by Django 5.2.4 on 2025-10-23 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0010_alter_banner_name_alter_banner_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='accept_border_color',
            field=models.CharField(default='#E5E7EB', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='accept_border_radius_px',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='banner',
            name='accept_border_width_px',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='banner',
            name='prefs_border_color',
            field=models.CharField(default='#E5E7EB', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='prefs_border_radius_px',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='banner',
            name='prefs_border_width_px',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='banner',
            name='reject_border_color',
            field=models.CharField(default='#E5E7EB', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='reject_border_radius_px',
            field=models.PositiveSmallIntegerField(default=8),
        ),
        migrations.AddField(
            model_name='banner',
            name='reject_border_width_px',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='banner',
            name='show_cookieguard_logo',
            field=models.BooleanField(default=True),
        ),
    ]
