# Generated by Django 5.2.4 on 2025-11-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0011_banner_accept_border_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
