# Generated by Django 5.2.4 on 2025-11-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0012_banner_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='text_color',
            field=models.CharField(default='#111827', max_length=20),
        ),
    ]
