# Generated by Django 5.2.4 on 2025-12-08 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0013_banner_text_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='cookie_policy_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
