# Generated by Django 5.2.4 on 2025-12-20 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0014_banner_cookie_policy_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='gradient_color_1',
            field=models.CharField(default='#6366f1', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='gradient_color_2',
            field=models.CharField(default='#8b5cf6', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='gradient_color_3',
            field=models.CharField(default='#d946ef', max_length=20),
        ),
        migrations.AddField(
            model_name='banner',
            name='gradient_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
