# Generated by Django 5.2.4 on 2025-12-21 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0015_add_gradient_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='gradient_speed',
            field=models.FloatField(default=3.0),
        ),
    ]
