# Generated by Django 5.2.4 on 2025-12-21 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banners', '0016_add_gradient_speed'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='gradient_persist',
            field=models.BooleanField(default=False),
        ),
    ]
