# Generated by Django 5.2.4 on 2025-08-24 03:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='billing_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='billingprofile',
            index=models.Index(fields=['stripe_customer_id'], name='billing_bil_stripe__499435_idx'),
        ),
        migrations.AddIndex(
            model_name='billingprofile',
            index=models.Index(fields=['subscription_id'], name='billing_bil_subscri_47d4d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='billingprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('stripe_customer_id__isnull', True), _negated=True), fields=('stripe_customer_id',), name='uniq_stripe_customer_when_set'),
        ),
    ]
