# Generated by Django 5.2.4 on 2025-08-31 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='trial_used',
            field=models.BooleanField(default=False),
        ),
    ]
