# Generated by Django 5.2.4 on 2025-12-22 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_billingprofile_plan_tier_auditlog_usagerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerecord',
            name='warning_100_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='warning_80_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usagerecord',
            name='warning_hard_limit_sent',
            field=models.BooleanField(default=False),
        ),
    ]
