# Generated by Django 5.2.4 on 2026-01-04 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_add_usage_warning_thresholds'),
    ]

    operations = [
        migrations.AddField(
            model_name='usagerecord',
            name='warning_70_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='billingprofile',
            name='plan_tier',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('multi_site', 'Multi-Site')], default='free', max_length=20),
        ),
    ]
