# Generated by Django 5.2.4 on 2025-09-02 06:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banners', '0001_initial'),
        ('domains', '0004_alter_domain_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(choices=[('accept', 'Accept'), ('reject', 'Reject'), ('prefs', 'Preferences')], max_length=20)),
                ('categories', models.JSONField(default=dict)),
                ('truncated_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_logs', to='banners.banner')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='domains.domain')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
