# Generated by Django 5.2.4 on 2025-09-14 23:40

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consentlog',
            name='banner_version',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consentlog',
            name='consent_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
