# Generated by Django 5.2.4 on 2025-08-30 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0003_domain_created_by_domain_industry_domain_is_ready'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='url',
            field=models.URLField(max_length=500),
        ),
    ]
