# Generated by Django 5.2.4 on 2025-09-30 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0004_alter_domain_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='embed_key',
            field=models.CharField(blank=True, default='', max_length=40, unique=True),
        ),
    ]
