# Generated by Django 5.2.4 on 2025-12-08 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0005_alter_domain_embed_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('necessary', 'Strictly Necessary'), ('preferences', 'Preferences'), ('analytics', 'Analytics'), ('marketing', 'Marketing')], max_length=20)),
                ('script_name', models.CharField(help_text='e.g., Google Analytics, Facebook Pixel', max_length=200)),
                ('script_pattern', models.TextField(help_text="URL pattern or selector to block (e.g., 'googletagmanager.com/gtag')")),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookie_categories', to='domains.domain')),
            ],
            options={
                'verbose_name_plural': 'Cookie categories',
                'unique_together': {('domain', 'script_name')},
            },
        ),
    ]
