# consents/management/commands/seed_consents.py

from django.core.management.base import BaseCommand
from django.utils import timezone
from datetime import timedelta
import random

from consents.models import ConsentLog
from domains.models import Domain
from banners.models import Banner


class Command(BaseCommand):
	help = "Seed dummy consent logs for testing analytics"

	def handle(self, *args, **options):
		# 1) Get a domain to attach everything to
		domain = Domain.objects.first()
		if not domain:
			self.stderr.write(
				self.style.ERROR(
					"No Domain found. Create at least one domain (via admin or API) and run again."
				)
			)
			return

		# 2) Get or create a banner
		banner = Banner.objects.first()
		if not banner:
			banner = Banner.objects.create(
				name="Demo Banner",
				title="We use cookies 🍪",
				description="This is a demo banner generated by the seed_consents command.",
			)
			# attach it to the domain via M2M
			banner.domains.add(domain)
			self.stdout.write(
				self.style.NOTICE(
					f"Created demo Banner(id={banner.id}) and attached it to Domain(id={domain.id})."
				)
			)
		else:
			# make sure this banner is attached to the domain
			banner.domains.add(domain)

		self.stdout.write(
			self.style.NOTICE(
				f"Seeding consents for domain={domain.id} and banner={banner.id} ({banner.name or banner.title})"
			)
		)

		choices = ["accept", "reject", "prefs"]

		# 3) Create dummy logs spread across last 14 days
		for _ in range(200):
			days_ago = random.randint(0, 14)
			timestamp = timezone.now() - timedelta(days=days_ago)

			ConsentLog.objects.create(
				banner=banner,
				domain=domain,
				banner_version=banner.version,
				choice=random.choices(
					choices,
					weights=[0.7, 0.25, 0.05],  # 70% accept, 25% reject, 5% prefs
				)[0],
				categories={"analytics": True, "ads": False},
				truncated_ip=f"10.0.0.{random.randint(1, 200)}",
				user_agent="SeederTest/1.0",
				created_at=timestamp,
			)

		self.stdout.write(self.style.SUCCESS("Seeded 200 dummy consent logs!"))
