# Generated by Django 5.2.4 on 2025-12-31 10:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('domains', '0006_cookiecategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CookieDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('domain_pattern', models.CharField(db_index=True, help_text="Domain pattern, e.g., '.google.com' or 'facebook.com'", max_length=255)),
                ('category', models.CharField(choices=[('necessary', 'Strictly Necessary'), ('functional', 'Functional'), ('analytics', 'Analytics'), ('marketing', 'Marketing/Advertising'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, help_text='What this cookie does')),
                ('provider', models.CharField(blank=True, help_text='e.g., Google Analytics, Facebook', max_length=100)),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('times_classified', models.PositiveIntegerField(default=0)),
                ('classification_confidence', models.FloatField(default=0, help_text='0-1 score based on agreement between user classifications')),
                ('votes_necessary', models.PositiveIntegerField(default=0)),
                ('votes_functional', models.PositiveIntegerField(default=0)),
                ('votes_analytics', models.PositiveIntegerField(default=0)),
                ('votes_marketing', models.PositiveIntegerField(default=0)),
                ('votes_other', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-times_seen'],
                'indexes': [models.Index(fields=['name'], name='scanner_coo_name_39158c_idx'), models.Index(fields=['domain_pattern'], name='scanner_coo_domain__abc56b_idx'), models.Index(fields=['category'], name='scanner_coo_categor_cd27b5_idx'), models.Index(fields=['-times_seen'], name='scanner_coo_times_s_c5fed3_idx')],
                'unique_together': {('name', 'domain_pattern')},
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('result', models.JSONField(default=dict, help_text='Full scan result JSON')),
                ('cookies_found', models.PositiveIntegerField(default=0)),
                ('has_consent_banner', models.BooleanField(default=False)),
                ('compliance_score', models.IntegerField(default=0)),
                ('first_party_count', models.PositiveIntegerField(default=0)),
                ('third_party_count', models.PositiveIntegerField(default=0)),
                ('tracker_count', models.PositiveIntegerField(default=0)),
                ('unclassified_count', models.PositiveIntegerField(default=0)),
                ('issues', models.JSONField(default=list)),
                ('pages_scanned', models.PositiveIntegerField(default=1)),
                ('duration', models.FloatField(default=0, help_text='Duration in seconds')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
                ('domain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='domains.domain')),
            ],
            options={
                'ordering': ['-scanned_at'],
            },
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('expires', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('First-party', 'First-party'), ('Third-party', 'Third-party')], max_length=20)),
                ('category', models.CharField(choices=[('necessary', 'Strictly Necessary'), ('functional', 'Functional'), ('analytics', 'Analytics'), ('marketing', 'Marketing/Advertising'), ('other', 'Other')], default='other', max_length=20)),
                ('classification', models.CharField(default='Unclassified', max_length=50)),
                ('user_category', models.CharField(blank=True, choices=[('necessary', 'Strictly Necessary'), ('functional', 'Functional'), ('analytics', 'Analytics'), ('marketing', 'Marketing/Advertising'), ('other', 'Other')], max_length=20, null=True)),
                ('user_description', models.TextField(blank=True)),
                ('definition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookie_instances', to='scanner.cookiedefinition')),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookies', to='scanner.scanresult')),
            ],
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['domain', '-scanned_at'], name='scanner_sca_domain__c1d08f_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['-scanned_at'], name='scanner_sca_scanned_4b98e5_idx'),
        ),
    ]
