# Generated by Django 5.2.4 on 2025-08-24 03:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('has_consent_banner', models.BooleanField(default=False)),
                ('compliance_score', models.IntegerField()),
                ('first_party_count', models.PositiveIntegerField()),
                ('third_party_count', models.PositiveIntegerField()),
                ('tracker_count', models.PositiveIntegerField()),
                ('unclassified_count', models.PositiveIntegerField()),
                ('issues', models.JSONField(default=list)),
                ('duration', models.FloatField(help_text='Duration in seconds')),
                ('scanned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cookie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('domain', models.CharField(max_length=255)),
                ('path', models.CharField(max_length=255)),
                ('expires', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('First-party', 'First-party'), ('Third-party', 'Third-party')], max_length=20)),
                ('classification', models.CharField(default='Unclassified', max_length=50)),
                ('scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cookies', to='scanner.scanresult')),
            ],
        ),
    ]
