# Generated by Django 5.2.4 on 2025-12-22 09:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domains', '0006_cookiecategory'),
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanresult',
            options={'ordering': ['-scanned_at']},
        ),
        migrations.AddField(
            model_name='scanresult',
            name='cookies_found',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='domain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scan_results', to='domains.domain'),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='pages_scanned',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='scanresult',
            name='result',
            field=models.JSONField(default=dict, help_text='Full scan result JSON'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='compliance_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='duration',
            field=models.FloatField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='first_party_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='third_party_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='tracker_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='scanresult',
            name='unclassified_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['domain', '-scanned_at'], name='scanner_sca_domain__c1d08f_idx'),
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['-scanned_at'], name='scanner_sca_scanned_4b98e5_idx'),
        ),
    ]
