# Generated by Django 5.2.4 on 2025-12-31 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_update_scanresult_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookie',
            name='category',
            field=models.CharField(choices=[('necessary', 'Strictly Necessary'), ('functional', 'Functional'), ('analytics', 'Analytics'), ('marketing', 'Marketing/Advertising'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='cookie',
            name='user_category',
            field=models.CharField(blank=True, choices=[('necessary', 'Strictly Necessary'), ('functional', 'Functional'), ('analytics', 'Analytics'), ('marketing', 'Marketing/Advertising'), ('other', 'Other')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cookie',
            name='user_description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='CookieDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('domain_pattern', models.CharField(db_index=True, help_text="Domain pattern, e.g., '.google.com' or 'facebook.com'", max_length=255)),
                ('category', models.CharField(choices=[('necessary', 'Strictly Necessary'), ('functional', 'Functional'), ('analytics', 'Analytics'), ('marketing', 'Marketing/Advertising'), ('other', 'Other')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, help_text='What this cookie does')),
                ('provider', models.CharField(blank=True, help_text='e.g., Google Analytics, Facebook', max_length=100)),
                ('times_seen', models.PositiveIntegerField(default=1)),
                ('times_classified', models.PositiveIntegerField(default=0)),
                ('classification_confidence', models.FloatField(default=0, help_text='0-1 score based on agreement between user classifications')),
                ('votes_necessary', models.PositiveIntegerField(default=0)),
                ('votes_functional', models.PositiveIntegerField(default=0)),
                ('votes_analytics', models.PositiveIntegerField(default=0)),
                ('votes_marketing', models.PositiveIntegerField(default=0)),
                ('votes_other', models.PositiveIntegerField(default=0)),
                ('is_verified', models.BooleanField(default=False, help_text='Manually verified by admin')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-times_seen'],
                'indexes': [models.Index(fields=['name'], name='scanner_coo_name_39158c_idx'), models.Index(fields=['domain_pattern'], name='scanner_coo_domain__abc56b_idx'), models.Index(fields=['category'], name='scanner_coo_categor_cd27b5_idx'), models.Index(fields=['-times_seen'], name='scanner_coo_times_s_c5fed3_idx')],
                'unique_together': {('name', 'domain_pattern')},
            },
        ),
        migrations.AddField(
            model_name='cookie',
            name='definition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cookie_instances', to='scanner.cookiedefinition'),
        ),
    ]
